### ISSUE TITLE
InfoWindow does not account for enableAltitude = false on panning

### ISSUE THREAD

**Issue by joric** [maptalks/maptalks.js#2354]
InfoWindow doesn't accurately follow the markers on panning when `enableAltitude` is set to `false`. There's always parallax effect even when all markers are drawn with a zero z-coordinate so InfoWindow looks completely detached from the markers. 

There are no workarounds for that except changing marker z-coordinate to zero and back and it basicaly would need reloading the entire map. I need dynamic `enableAltitude` to work.

**Comment by joric** [comment]
@deyihu I built your branch in the PR, but it doesn't fix the problem. I use dynamic enableAltitude on viewchange, like this:
```js
  map.on('viewchange', e=> {
      vectorLayer.setOptions({enableAltitude: map.getPitch()!=0});
  });
```
Both InfoWindow and markers lose parallax effect when pitch is set to 0 but InfoWindow still doesn't match the marker origin point, it depends on previous position of the map.

https://github.com/maptalks/maptalks.js/assets/852547/3741093d-2413-4082-b7c5-70288528d431

**Comment by deyihu** [comment]
@joric  The latest code for PR may have been fixed

**Comment by joric** [comment]
@deyihu all good now. Thank you!

**Comment by joric** [comment]
@deyihu Oh. Not quite. There's still an issue when the info window is created (not animated along with the enableAltitude change, but created when enableAltitude is already false), coordinates are off.

Also there's an issue with the actual click area, despite the cursor changes to hand, InfoWindow doesn't open. It opens only if I click slightly to the side where the marker supposed to be if altitude was enabled. So it seems a little bit more complicated.

https://github.com/maptalks/maptalks.js/assets/852547/18df3c8d-a7df-46a6-aae7-cfdce64aaee4

**Comment by joric** [comment]
#2355 up to 196cca6 seem to fix the issues.
